package cn.edu.uestc.aone.web.helloworld.dao.rdb;

import java.util.List;

import cn.edu.uestc.aone.web.helloworld.model.po.rdb.Department;

/**
 * Department的MyBatis Mapper接口，对应department表，包含一系列CRUD方法
 * Created by Carter Peng 2018/10/14
 */
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 30 21:35:27 CST 2018
     */
    int deleteByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 30 21:35:27 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 30 21:35:27 CST 2018
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 30 21:35:27 CST 2018
     */
    Department selectByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 30 21:35:27 CST 2018
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 30 21:35:27 CST 2018
     */
    int updateByPrimaryKey(Department record);

    /**
     * 查询department表中所有部门
     * @return List<Department>
     */
    List<Department> selectAll();
}